
#' Create a Bubble Plot for PCI Visualization
#'
#' This function generates a bubble plot to visualize the results of the PCI
#' calculation. It shows the mean action acceptability on the y-axis and the PCI
#' value as the size of the bubbles.
#'
#' @param df3 A data frame generated by the 'pci' function, containing the PCI
#' values and other statistics.
#' @param scale_type The scale type used: 'bipolar' or 'unipolar'. Default is 'bipolar'.
#' @param ylim_range For 'bipolar' scale, the range of the y-axis. Must be an integer between 1 and 4.
#' @param unipolar_ylim A numeric vector of length 2 specifying the y-axis limits for 'unipolar' scale.
#' @param xlab The label for the x-axis. Default is an empty string.
#' @param ylab The label for the y-axis. Default is 'Action acceptability'.
#' @param title Optional title for the plot. Default is NULL.
#' @param bubble_color The fill color of the bubbles. Default is 'gray80'.
#' @param bubble_stroke The border color of the bubbles. Default is 'black'.
#'
#' @return A ggplot2 object representing the bubble plot.
#'
#' @details
#' The bubble plot displays the 'Mean' value on the y-axis and the PCI value as the size of the bubbles.
#' It helps to visualize the relationship between action acceptability (mean score) and the potential
#' for conflict index (PCI) for each category in the dataset.
#'
#' @examples
#' data <- data.frame(
#'   Category = rep(c('A', 'B', 'C'), each = 3),
#'   Value = c(-1, 0, 1, -1, 0, 1, -1, 0, 1)
#' )
#' df2 <- counting(data)
#' df3 <- pci(df2)
#' bubble(df3)
#'
#' @import ggplot2
#' @export
bubble <- function(df3,
                   scale_type = c('bipolar', 'unipolar'),
                   ylim_range = 4,
                   unipolar_ylim = c(1, 9),
                   xlab = '',
                   ylab = 'Action acceptability',
                   title = NULL,
                   bubble_color = 'gray80',
                   bubble_stroke = 'black') {
  scale_type <- match.arg(scale_type)

  if (scale_type == 'unipolar') {
    if (!is.numeric(unipolar_ylim) || length(unipolar_ylim) != 2) {
      stop('For unipolar scale, unipolar_ylim must be a numeric vector of length 2.')
    }
    y_limits <- unipolar_ylim
  } else {
    if (!ylim_range %in% 1:4) {
      stop('For bipolar scale, ylim_range must be 1, 2, 3, or 4.')
    }
    y_limits <- c(-ylim_range, ylim_range)
  }

  p <- ggplot(df3, aes(x = name, y = Mean, size = PCI)) +
    geom_hline(yintercept = 0, colour = 'black') +
    geom_point(shape = 21, fill = bubble_color, color = bubble_stroke, show.legend = TRUE) +
    geom_text(aes(label = round(PCI, 2)),
              nudge_y = 0.35, nudge_x = 0.1, size = 5) +
    ylab(ylab) + xlab(xlab) +
    ylim(y_limits) +
    scale_size_area(max_size = 14) +
    theme_minimal() +
    theme(panel.grid.major.y = element_blank(),
          panel.grid.minor.y = element_blank(),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          axis.title.x = element_text(size = 16),
          axis.title.y = element_text(size = 16),
          axis.text.x = element_text(size = 14, angle = 45, vjust = 1, hjust = 1),
          axis.text.y = element_text(size = 14),
          axis.line.x = element_line(colour = 'white'),
          axis.line.y = element_line(colour = 'black'),
          axis.ticks = element_line(colour = 'black'),
          legend.key.size = unit(1, 'cm'),
          legend.key.height = unit(1, 'cm'),
          legend.key.width = unit(1, 'cm'),
          legend.title = element_text(size = 16),
          legend.text = element_text(size = 14))

  if (!is.null(title)) {
    p <- p + ggtitle(title) +
      theme(plot.title = element_text(size = 18, face = 'bold', hjust = 0.5))
  }

  return(p)
}

